version: "3.9"

services:
  sonar:
    image: sonarqube:25.11.0.114957-community
    depends_on:
      - db
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_logs:/opt/sonarqube/logs
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - sonar

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - start
      - --all
      - --config
      - /etc/ngrok.yml
    ports:
      - "4040:4040"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - sonar

networks:
  sonar:
    driver: bridge
